

trigger:
- master

pool: abhi

steps:
- script: |
      git submodule init
      git submodule update --remote warehouse/resource-types
      docker build -t dutyfree .
      docker run dutyfree -p 80:9090
#      docker-compose up --build
#      docker build -t dutyfree .
#      docker run dutyfree -p 80:9090
