trigger:
- master

pool: abhi

jobs:
- job: A
  steps:
      - script: |
            git submodule init
            git submodule update --remote warehouse/resource-types
- job: B
  steps:
      - script: |
            cd warehouse
#      docker-compose up --build
#      docker build -t dutyfree .
#      docker run dutyfree -p 80:9090

