
trigger:
- master

pool: abhi

variables: 
  imageName: dutyfree

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - script: |
        docker build -t $(imageName):latest .
        docker run dutyfree -p 80:9090
