trigger:
- master

pool: abhi
stages:
- stage: 1
  jobs:
  - job: codeCheck
    steps:
        - script: |
              git submodule init
              git submodule update --remote warehouse/resource-types
- stage: 2
  jobs:
  - job: Building
    steps:
        - script: |
              docker build -t dutyfree .
              docker run  -td -p 9090:9090 dutyfree
#      docker-compose up --build
#      docker build -t dutyfree .
#      docker run dutyfree -p 80:9090
