trigger:
- master

pool: abhi
stages:
- stage: Check
  jobs:
  - job: codeCheck
    steps:
        - script: |
              git submodule init
              git submodule update --remote warehouse/resource-types
- stage: Test
  jobs:
  - job: testing_Backend
    steps:
        - script: |
              cd warehouse
              ginkgo -r -keepGoing .
              cd ..
  - job: testing_Frontend
    steps:
        - script: |
              cd warehouse && yarn install && yarn test
              cd ..
- stage: Build
  jobs:
  - job: TokenAddition
    steps:
        - script: |
              echo 'ENV GH_TOKEN=$(TOKEN1)' Dockerfile
  - job: PushingImagetoHeroku
    steps:
        - script: |
              echo 'ENV GH_TOKEN=$(TOKEN1)' Dockerfile
              heroku container:push web --app morning-harbor-44928
  - job: ReleasingContainer
    steps:
      - script: |
              heroku container:release web
#      docker-compose up --build
#      docker build -t dutyfree .
#      docker run dutyfree -p 80:9090
