trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: |
        git clone https://github.com/AnmolVirdi/resource-types-website
        cd resource-types-website
        docker build -t dutyfree
        docker run dutyfree -p 9090:9090